apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
        - name: analytics
          image: janindudocker/analytics-service:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service-svc
  annotations:
    prometheus.io/scrape: "true"   # Tell Prometheus to scrape this Service
    prometheus.io/port: "3000"     # Port where metrics are exposed
    prometheus.io/path: "/metrics" # Path to metrics endpoint
spec:
  selector:
    app: analytics-service
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30020
