apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order
        image: janindudocker/order-service:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: order-service-svc
  annotations:
    prometheus.io/scrape: "true"   # Tell Prometheus to scrape this Service
    prometheus.io/port: "80"       # Port where metrics are exposed
    prometheus.io/path: "/metrics" # Path to metrics endpoint
spec:
  selector:
    app: order-service
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30011
